# Generated by Django 5.2.6 on 2025-11-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='date_consultation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
