# Generated by Django 5.2.6 on 2025-11-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_alter_consultation_date_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=40)),
                ('quantite', models.IntegerField()),
                ('contenant', models.CharField(max_length=40)),
                ('duree_en_jours', models.IntegerField()),
                ('dosage', models.IntegerField()),
                ('instructions_utilisations', models.TextField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medico.consultation')),
            ],
        ),
    ]
