# Generated by Django 5.2.6 on 2025-11-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_traitement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackMarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_item', models.CharField(max_length=40)),
                ('prix', models.FloatField()),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
