# Generated by Django 5.2.6 on 2025-11-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_purchaseditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedItem',
        ),
    ]
